server:
  port: 8081

spring:
  application:
    name: log-monitoring

  # Redis
  redis:
    host: localhost
    port: 6379

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log-monitoring
      auto-offset-reset: latest

  # Elasticsearch
  elasticsearch:
    uris: http://localhost:9200
    # if you enable security later:
    # username: elastic
    # password: changeme

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
